//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplicationTests.MyFisrServiceWCFReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyFisrServiceWCFReference.IMyFirstService")]
    public interface IMyFirstService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetData", ReplyAction="http://tempuri.org/IMyFirstService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetData", ReplyAction="http://tempuri.org/IMyFirstService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMyFirstService/GetDataUsingDataContractResponse")]
        WcfServiceApplication.CompositeType GetDataUsingDataContract(WcfServiceApplication.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMyFirstService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IMyFirstService/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WcfServiceApplication.CompositeType> GetDataUsingDataContractAsync(WcfServiceApplication.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMyFirstServiceChannel : WcfServiceApplicationTests.MyFisrServiceWCFReference.IMyFirstService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyFirstServiceClient : System.ServiceModel.ClientBase<WcfServiceApplicationTests.MyFisrServiceWCFReference.IMyFirstService>, WcfServiceApplicationTests.MyFisrServiceWCFReference.IMyFirstService {
        
        public MyFirstServiceClient() {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyFirstServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyFirstServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public WcfServiceApplication.CompositeType GetDataUsingDataContract(WcfServiceApplication.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<WcfServiceApplication.CompositeType> GetDataUsingDataContractAsync(WcfServiceApplication.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
