//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplicationTests.MySecondWCFServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MySecondWCFServiceReference.IMySecondWCFService")]
    public interface IMySecondWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySecondWCFService/GetFactorialNumber", ReplyAction="http://tempuri.org/IMySecondWCFService/GetFactorialNumberResponse")]
        int GetFactorialNumber(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySecondWCFService/GetFactorialNumber", ReplyAction="http://tempuri.org/IMySecondWCFService/GetFactorialNumberResponse")]
        System.Threading.Tasks.Task<int> GetFactorialNumberAsync(int number);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMySecondWCFServiceChannel : WcfServiceApplicationTests.MySecondWCFServiceReference.IMySecondWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MySecondWCFServiceClient : System.ServiceModel.ClientBase<WcfServiceApplicationTests.MySecondWCFServiceReference.IMySecondWCFService>, WcfServiceApplicationTests.MySecondWCFServiceReference.IMySecondWCFService {
        
        public MySecondWCFServiceClient() {
        }
        
        public MySecondWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MySecondWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySecondWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySecondWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetFactorialNumber(int number) {
            return base.Channel.GetFactorialNumber(number);
        }
        
        public System.Threading.Tasks.Task<int> GetFactorialNumberAsync(int number) {
            return base.Channel.GetFactorialNumberAsync(number);
        }
    }
}
