//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceApplicationTests.MySecondWCFServiceReference {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnumOperator", Namespace="http://schemas.datacontract.org/2004/07/WcfServiceApplication")]
    internal enum EnumOperator : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Plus = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Minus = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Times = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MySecondWCFServiceReference.IMySecondWCFService")]
    internal interface IMySecondWCFService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySecondWCFService/GetFactorialNumber", ReplyAction="http://tempuri.org/IMySecondWCFService/GetFactorialNumberResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IMySecondWCFService/GetFactorialNumberFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        int GetFactorialNumber(int number);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMySecondWCFService/ApplyOperation", ReplyAction="http://tempuri.org/IMySecondWCFService/ApplyOperationResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.ServiceModel.FaultException), Action="http://tempuri.org/IMySecondWCFService/ApplyOperationFaultExceptionFault", Name="FaultException", Namespace="http://schemas.datacontract.org/2004/07/System.ServiceModel")]
        int ApplyOperation(int number1, int number2, WcfServiceApplicationTests.MySecondWCFServiceReference.EnumOperator enumOperator);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal interface IMySecondWCFServiceChannel : WcfServiceApplicationTests.MySecondWCFServiceReference.IMySecondWCFService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    internal partial class MySecondWCFServiceClient : System.ServiceModel.ClientBase<WcfServiceApplicationTests.MySecondWCFServiceReference.IMySecondWCFService>, WcfServiceApplicationTests.MySecondWCFServiceReference.IMySecondWCFService {
        
        public MySecondWCFServiceClient() {
        }
        
        public MySecondWCFServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MySecondWCFServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySecondWCFServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MySecondWCFServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int GetFactorialNumber(int number) {
            return base.Channel.GetFactorialNumber(number);
        }
        
        public int ApplyOperation(int number1, int number2, WcfServiceApplicationTests.MySecondWCFServiceReference.EnumOperator enumOperator) {
            return base.Channel.ApplyOperation(number1, number2, enumOperator);
        }
    }
}
